### ISSUE TITLE
Icon are not rendered in ckeditor

### ISSUE THREAD

**Issue by FabriceSalvaire** [django-cms/djangocms-bootstrap4#101] opened 2019-12-24 19:38 UTC
a workaround is to use the source mode to see the corresponding xhtml code.

**Comment by sq9mev** [comment] 2020-01-29 13:58
Confirmed with djangocms_bootstrap4-1.5.0, both left and right are getting "undefined" class instead of eg. "far" for Font Awesome 5 Regular iconset.

Looks exactly like #83 which is closed with message "This has been fixed in 1.4.0"…

The issue is observer with:

- djangocms_bootstrap4-1.5.0
- djangocms_link-2.5.0
- djangocms_icon-1.5.0
- djangocms_picture-2.4.0

**Comment by sq9mev** [comment] 2020-01-30 08:38
I've found the cause in bundle.base.js, here's the patch (this file is compressed somehow, so uncomressed it with js-beautify and continued to work on it uncompressed).

How should i work on js files in uncompressed form? Commits on js scripts are unreadable in this repo as for now (single diff contains a whole linie), so the change history is lost.

I'll provide PR in a moment containing original bundle.base.js edited by hand.

```
--- bundle.base.js      2020-01-30 09:09:59.602402013 +0100
+++ _bundle.base.js     2020-01-30 09:08:22.255733764 +0100
@@ -3828,7 +3828,7 @@
                             try {
                                 c = JSON.parse(u)
                             } catch (e) {}
-                            var l = i.find("select option:selected").data("iconset-prefix");
+                            var l = i.find("select option:selected").data("prefix");
                             if ("string" == typeof c) o()(".js-icon-" + (s ? "left" : "right")).html('\n                    <span class="' + l + " " + a + '"></span>\n                ');
                             else {
                                 var f = e.container.data("static"),


```

**Comment by corentinbettiol** [comment] 2020-04-21 08:01
I think the proper way to fix this is to update the "source" files in `private/js` folder, and then to run `gulp` in order to compile them into the *.bundle.js ones.

**Comment by foarsitter** [comment] 2020-05-11 11:45
In [link.html](https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_link/templates/djangocms_bootstrap4/link/default/link.html) a include is done of [djangocms_icon/includes/icon.html](https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_link/templates/djangocms_bootstrap4/link/default/link.html) with `icon_class=instance.icon_left instance=instance.icon_left`. But `i nstance` is a string and not a plugin. 

For my project overriding the link.html template solves the problem:
templates/djangocms_bootstrap4/link/default/link.html

```
{% load cms_tags %}{% spaceless %}
  {# this needs to be in one line for rendering purpose #}
<a
        href="{{ link }}"
        {% if instance.target %}
        target="{{ instance.target }}"
        {% endif %}

        {% if instance.attributes %}
          {{ instance.attributes_str }}
        {% endif %}
>
  {% if instance.icon_left %}
    <i class="{{ instance.icon_left }}"></i>
  {% endif %}
  {% for plugin in instance.child_plugin_instances %}
    {% render_plugin plugin %}
  {% empty %}
    {{ instance.name }}
  {% endfor %}

  {% if instance.icon_right %}
    <i class="{{ instance.icon_right }}"></i>
  {% endif %}
</a>
{% endspaceless %}
```

**Closed as completed** 2020-08-27 13:11 UTC
