### ISSUE TITLE
documentation for collapse

### ISSUE THREAD

**Issue by electroniceagle** [django-cms/djangocms-bootstrap4#36] opened 2018-04-22 13:09 UTC
I'm having difficulty understanding how the collapse behavior works.  What is the relationship between the three plugins?  I'd be happy to contribute some unit tests and/or examples.  Even a screen shot of structure view of a working example would be helpful.

**Comment by jamesprnich** [comment] 2018-08-02 00:51
@electroniceagle Did you figure this out?

**Comment by electroniceagle** [comment] 2018-10-17 20:12
No, went to tabs temporarily.  Not a burning issue.

**Comment by oliashford** [comment] 2018-11-01 16:20
I am having the same issue.

Currently I have this setup:

![image](https://user-images.githubusercontent.com/38863491/47864527-b77bc980-ddf1-11e8-99e2-ac22ef9c9367.png)

The current behaviour is I click "Show Part 1" and the link itself (Collapse Trigger > Text) animates 'show' then I click again and it animates 'hide'... and is gone.

Would be great to just see a screengrab of a working collapse (even better multiple collapses working as a concertina)

**Comment by oliashford** [comment] 2018-11-02 14:45
I was pointed to this change:

https://github.com/divio/djangocms-bootstrap4/pull/20/commits/dee89d8627676b18c4fb731e34cb2797266aab9f

by Daniele Procida

I restored the "container-" and "trigger-" that were removed in both files to resolve the issue. Will submit a fix as soon as i get a chance.

**Comment by vxsx** [comment] 2018-11-05 08:12
The issue is resolved, will be released soon

the usage outlined here is correct https://github.com/divio/djangocms-bootstrap4/issues/36#issuecomment-435096415

docs PRs are always welcome

**Closed as completed** 2018-11-13 17:12 UTC
Labels: status: ready to be merged
